name: resize

dependencies:
  - base >= 4.7 && < 5
  - containers
  - hip

ghc-options:
  - -O0
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-matches
  - -Wno-name-shadowing
  - -Wno-type-defaults

default-extensions:
  - FlexibleContexts
  - StrictData

library:
  source-dirs: src

executables:
  resize:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - resize
